### ISSUE TITLE
Password rotation failed to due login issue RDS SQL Server Enterprise Edition when SSL is enforced

### ISSUE THREAD

**Issue by Steven-N** [aws-samples/aws-secrets-manager-rotation-lambdas#23] opened 2019-10-27 19:07 UTC
Hi folks!

I seem to have come across an issue with the RDS SQL Server rotation lambda. I'm specifically seeing this with "SecretsManagerRDSSQLServerRotationSingleUser".

Steps to reproduce:
1. Deploy RDS DB Instance running SQL Server enterprise edition.
2. Associate an RDS Parameter group with this DB instance with the parameter "rds.force_ssl" set to "1".
3. Create a new secret in secrets manager and configure it to manage the rotation of the master user for the DB instance.

Errors:
- Check the lambda logs in cloudwatch for the secret rotation lambda. There will be an error stating `setSecret: Unable to log into database with previous, current, or pending secret of secret arn <secret arn>`
- I also slightly modified the lambda to log the error from SQL Server, and received this message: `(20002, 'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed`.

I've done some research, and it seems that the version of `pymssql` which this lambda uses (pymssql v2.1.1) is not packaged with a version of FreeTDS which supports SSL connections to SQL Server.

I've confirmed that this is my issue as I've tried disabling the `rds.force_ssl` paramater (i.e. setting the value to "0") which fixes this issue.

I found a related workaround here for "pymsql" (used in the RDS MySQL rotation lambda): https://aws.amazon.com/premiumsupport/knowledge-center/rotate-secret-db-ssl/ which mentions to update the connection to have an additional parameter `ssl={'ca': './rds-combined-ca-bundle.pem'}`, however I do not believe that this is a support parameter in `pymssql`.

The Microsoft SQL documentation mentions that the supported python SQL driver is `pyodbc` (you can see that here https://docs.microsoft.com/en-us/sql/connect/python/python-driver-for-sql-server?view=sql-server-ver15). I've tested `pyodbc` connections to RDS SQL Server and it works well with SSL enabled on the parameter group.

Is there any chance of this issue being resolved by either creating this lambda with a newer version of `pymssql` and packaging it with a version of FreeTDS which supports SSL or possibly refactoring to use `pyodbc`? 

Thanks in advanced and let me know if you have any further questions!

**Comment by matthewcarlisle** [comment] 2020-05-12 22:41
Just spent a few hours diagnosing this exact issue, and now kicking myself for not looking at the Issues.  However, the lack of decent logging showed no indication that this would be the problem.  I'm seeing this on SQL Server 2017 Standard Edition.

**Comment by joebaro** [comment] 2021-05-05 23:46
Duplicate of https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/issues/14

**Comment by joebaro** [comment] 2021-05-05 23:46
https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/issues/14

**Closed by joebaro** 2021-05-05 23:46 UTC
Labels: duplicate
