### ISSUE TITLE
Expose Permission boundary for the IAM role

### ISSUE THREAD

**Issue by karthikkarnam** [aws-samples/aws-secrets-manager-rotation-lambdas#95] opened 2022-12-21 07:52 UTC
Greetings,

We use RDSMySQL and RDSPostgreSQL rotation lambda and we cant create an IAM role without a permission boundary which is been set organisation wide by our DE Team.

I was wondering if [PermissionsBoundary](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-permissionsboundary) can be exposed as an optional parameter for the deployment of this Serverless function?

Thanks

**Comment by jbct** [comment] 2023-02-28 22:15
Thank you for the request. I am closing this one as a duplicate of https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/issues/27 and we are investigating internally.

**Closed by jbct** 2023-02-28 22:15 UTC
